on:
  workflow_call:
    inputs:
      artifact_id:
        description: 'Artifact ID for Maven deployment.'
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Create Maven Settings
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>nexus</id>
                <username>${{ secrets.NEXUS_USERNAME }}</username>
                <password>${{ secrets.NEXUS_PASSWORD }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Upload Artifact to Nexus
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          NEXUS_URL: ${{ secrets.NEXUS_URL }}
        run: |
          # Step 1: Extract the full version from version.properties
          VERSION=$(grep "maven_version" target/classes/version.properties | cut -d'=' -f2 | tr -d '\r')
          echo "Extracted version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV
      
          # Step 2: Dynamically locate the JAR file matching the version
          JAR_FILE=$(ls target/*-${VERSION}.jar | head -n 1)
      
          if [ -z "$JAR_FILE" ]; then
            echo "Error: Could not find JAR file matching version $VERSION in target directory."
            exit 1
          fi
      
          echo "Deploying JAR file: $JAR_FILE to Nexus..."
      
          # Step 3: Deploy the JAR file to Nexus
          mvn deploy:deploy-file \
            -DgroupId=com.ocrespo \
            -DartifactId=${{ inputs.artifact_id }} \
            -Dversion=$VERSION \
            -Dpackaging=jar \
            -Dfile=$JAR_FILE \
            -DrepositoryId=nexus \
            -Durl=$NEXUS_URL